spring.application.name=server
spring.datasource.url=jdbc:postgresql://ep-tiny-sun-b29760ik-pooler.c-6.eu-central-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ZB3hak8qiKUm

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

neon.storage.endpoint=https://br-twilight-field-b252xil6.storage.c-6.eu-central-1.aws.neon.tech
neon.storage.access-key=nak_live_0565a525e4c843a48b78456886eedcb1
neon.storage.secret-key=nsk_live_4b6924e6124229af8690de373ba6cd29c55d887087ef85250e2ac3306cd18750
neon.storage.region=eu-central-1
neon.storage.bucket=storage

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
