spring.application.name=server
spring.datasource.url=jdbc:postgresql://ep-tiny-sun-b29760ik-pooler.c-6.eu-central-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ZB3hak8qiKUm

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
